name: Linting Shell Scripts

on:
  push:
    branches: [master, beta, develop]
  pull_request:
    branches: [master, beta, develop]
  schedule:

permissions: {}

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

        - name: (Lint) Run ShellCheck
          uses: ludeeus/action-shellcheck@master # v2.0.0
